before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $ON_EVENTS != *$TRAVIS_EVENT_TYPE* ]]; then exit; fi

language: php

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE

dist: precise

#Possible travis events (push, pull_request, cron, or api)
matrix:
  fast_finish: true
  include:
     - php: "5.6"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
     - php: "7.0"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
     - php: "7.1"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
     - php: "5.6"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=cron
     - php: "7.0"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=cron
     - php: "7.1"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=push,cron

addons:
  postgresql: 9.4

  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - redis

sudo: required

install:
  - chmod -R a+x config/Shared/ci/travis/
  - composer self-update && composer --version
  - composer install --no-interaction
  - config/Shared/ci/travis/install_elasticsearch.sh

before_script:
  - nvm install 6

  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777
  - chmod -R 777 data/

  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_default-devtest_DE.php
  - cp config/Shared/ci/travis/params_test_env.sh deploy/setup/params_test_env.sh

  - if [[ $TEST_GROUP == 'acceptance' ]]; then config/Shared/ci/travis/acceptance_env.sh; fi
  - if [[ $TEST_GROUP == 'acceptance' ]]; then ./setup_test -f; fi
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then ./setup_test -b; fi

  - vendor/bin/console twig:cache:warmer

script:
  - vendor/bin/phantomjs --webdriver=4444 > /dev/null &
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then vendor/bin/codecept run -x Acceptance -x Presentation -vvv ; fi
  - if [[ $TEST_GROUP == 'acceptance' ]]; then vendor/bin/codecept run -g Acceptance -g Presentation ; fi

  - if [[ $TRAVIS_PHP_VERSION == 7.0 && $TEST_GROUP == 'without-acceptance' ]] ; then vendor/bin/console code:sniff ; fi

notifications:
  email: false
