before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

language: php
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - env: TEST_GROUP=acceptance

addons:
  postgresql: 9.4

  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.dev
    - www.de.spryker.dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - elasticsearch
  - redis

sudo: required

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE
  matrix:
    - TEST_GROUP=without-acceptance
    - TEST_GROUP=acceptance

install:
  - composer self-update && composer --version
  - composer install --no-interaction

before_script:
  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_default-development_DE.php
  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_default-test.php

  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777

script:
  - vendor/bin/console propel:install -o
  - vendor/bin/console transfer:generate
  - vendor/bin/console setup:init-db
  - vendor/bin/console setup:search
  - vendor/bin/console import:demo-data

  - vendor/bin/console application:build-navigation-cache

  - chmod -R 777 data/
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then vendor/bin/codecept run -x Acceptance ; fi
  - if [[ $TEST_GROUP == 'acceptance' ]]; then vendor/bin/codecept run -g Acceptance ; fi

# Just in case you want to know about errors uncomment this
#  - cat /tmp/zed-error.log

  - vendor/bin/console collector:storage:export
  - vendor/bin/console collector:search:export

  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]] ; then vendor/bin/console code:sniff ; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]] ; then vendor/bin/console dev:dependency:build-tree ; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]] ; then vendor/bin/console dev:dependency:find-violations ; fi

notifications:
  email: false
