namespace: SprykerTest\%application%\%module%

paths:
    tests: .
    data: ../../../_data
    support: _support
    log: ../../../_output

coverage:
    enabled: true
    remote: false
    whitelist: { include: ['../../../../src/*'] }

suites:
    Business:
        path: Business
        class_name: %module%BusinessTester
        modules:
            enabled:
                - Asserts
                - \SprykerTest\Shared\Testify\Helper\Environment
                - \SprykerTest\Shared\Testify\Helper\ConfigHelper
                - \SprykerTest\Shared\Testify\Helper\LocatorHelper
                - \SprykerTest\Shared\Testify\Helper\DependencyHelper
                - \SprykerTest\Shared\Propel\Helper\TransactionHelper

    Communication:
        path: Communication
        class_name: %module%CommunicationTester
        modules:
            enabled:
                - Asserts
                - \SprykerTest\Shared\Testify\Helper\Environment
                - \SprykerTest\Shared\Testify\Helper\ConfigHelper
                - \SprykerTest\Shared\Testify\Helper\LocatorHelper
                - \SprykerTest\Shared\Testify\Helper\DependencyHelper
                - \SprykerTest\Shared\Propel\Helper\TransactionHelper

    Persistence:
        path: Persistence
        class_name: %module%PersistenceTester
        modules:
            enabled:
                - Asserts
                - \SprykerTest\Shared\Testify\Helper\Environment
                - \SprykerTest\Shared\Testify\Helper\ConfigHelper
                - \SprykerTest\Shared\Testify\Helper\LocatorHelper
                - \SprykerTest\Shared\Testify\Helper\DependencyHelper
                - \SprykerTest\Shared\Propel\Helper\TransactionHelper

    Presentation:
        path: Presentation
        class_name: %module%PresentationTester
        modules:
            enabled:
                - Asserts
                - \SprykerTest\Shared\Testify\Helper\Environment
                - \SprykerTest\Shared\Config\Helper\ConfigInit
                - \SprykerTest\Shared\Testify\Helper\LocatorHelper
                - WebDriver:
                    url: ''
                    browser: chrome
                    window_size: 1920x1080
                    host: 0.0.0.0
                    restart: false
                - \SprykerTest\Shared\Testify\Helper\DataCleanupHelper
                - \SprykerTest\Shared\Application\Helper\ZedHelper
                - \SprykerTest\Zed\ZedNavigation\Helper\BreadcrumbHelper
                - \SprykerTest\Zed\Gui\Helper\DataTableActionHelper
